### ISSUE TITLE
stream-bench.sh SETUP gets stuck

### ISSUE THREAD

**Issue by tolgasaglik** [yahoo/streaming-benchmarks#39]
It gets stuck when trying to do this step:

> Downloading from Datatorrent-Releases: https://www.datatorrent.com/maven/content/repositories/releases/org/apache/apex/apex-engine/3.4.0/apex-engine-3.4.0.pom

**Comment by jerrypeng** [comment]
oh its because datatorrent is no more

**Comment by tolgasaglik** [comment]
> oh its probably because datatorrent is no more

What to do then?

**Comment by jerrypeng** [comment]
either need to find another link for apex or remove apex from benchmark

**Comment by tolgasaglik** [comment]
> either need to find another link for apex or remove apex from benchmark

I do not need apex. I actually only need spark, flink, storm and samza(not here). I excluded it from the .sh file and pom.xml. 
Then I am getting a new error. So redis is gone too?

> make[1]: Leaving directory `/mnt/irisgpfs/users/tsaglik/big-data-framework-analysis/streaming-benchmarks/redis-3.0.5/src'
> Using cached File download-cache/kafka_2.10-0.8.2.1.tgz
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

Would you suggest another benchmark to test mentioned apps?
